package JavaCore.ZZgConcorencia.Teste;

import JavaCore.ZZgConcorencia.Dominio.Quote;
import JavaCore.ZZgConcorencia.Service.StoreServiceWithDiscount;

import javax.xml.namespace.QName;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Collectors;

public class CompletableFutureTeste04 {
    public static void main(String[] args) {
        StoreServiceWithDiscount service = new StoreServiceWithDiscount();
        searchPricesWithDIscountAsync(service);
    }

    private static  void searchPricesWithDIscount(StoreServiceWithDiscount service ){
        long start = System.currentTimeMillis();
        List<String> stores = List.of("Store1","Store2","Store3","Store4");
      //stores.forEach(s -> System.out.println(service.getPriceSync(s)));
        stores.stream()
                .map(service::getPriceSync)// stare:price:code
                .map(Quote::newQUate)
                .map(service::applyDIscount)
                .forEach(System.out::println);
        long end = System.currentTimeMillis();
        System.out.printf("Time passed to searchPricesSync %dms%n", (end - start));

    }
    private static  void searchPricesWithDIscountAsync(StoreServiceWithDiscount service ){
        long start = System.currentTimeMillis();
        List<String> stores = List.of("Store1","Store2","Store3","Store4");

        List<CompletableFuture<String>> completableFutures = stores.stream()
                //Getting the price osync starName:price:discountCode
                .map(s -> CompletableFuture.supplyAsync(() -> service.getPriceSync(s)))
                //Instanting a new quate from the string generated by getPriceSync
                .map(cf -> cf.thenApply(Quote::newQUate))
                //Composingf the first completable future
                .map(cf -> cf.thenCompose(quote -> CompletableFuture.supplyAsync(() -> service.applyDIscount(quote))))
                .collect(Collectors.toList());

        completableFutures.stream()
                .map(CompletableFuture::join)
                .forEach(System.out::println);


        long end = System.currentTimeMillis();
        System.out.printf("Time passed to searchPricesSync %dms%n", (end - start));

    }
}
